REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics'                                                       /v 'Enabled'                                       /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Control Panel\International'                                      /v 'BlockUserInputMethodsForSignIn'                /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\EventViewer'                                                      /v 'MicrosoftEventVwrDisableLinks'                 /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\FVE'                                                              /v 'EnableBDEWithNoTPM'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\FVE'                                                              /v 'UseAdvancedStartup'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\FVE'                                                              /v 'UseTPM'                                        /T 'REG_DWORD' /D '2'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\FVE'                                                              /v 'UseTPMKey'                                     /T 'REG_DWORD' /D '2'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\FVE'                                                              /v 'UseTPMKeyPin'                                  /T 'REG_DWORD' /D '2'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\FVE'                                                              /v 'UseTPMPIN'                                     /T 'REG_DWORD' /D '2'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds'                                          /v 'AllowBasicAuthInClear'                         /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds'                                          /v 'DisableEnclosureDownload'                      /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting'                                          /v 'DoReport'                                      /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting'                                          /v 'IncludeKernelFaults'                           /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting'                                          /v 'IncludeShutdownErrs'                           /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PCHealth\HelpSvc'                                                 /v 'Headlines'                                     /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Peernet'                                                          /v 'Disabled'                                      /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51'         /v 'ACSettingIndex'                                /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51'         /v 'DCSettingIndex'                                /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power\PowerSettings\3C0BC021-C8A8-4E07-A973-6B14CBCB2B7E'         /v 'ACSettingIndex'                                /T 'REG_DWORD' /D '4b0'                                    /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power\PowerSettings\3C0BC021-C8A8-4E07-A973-6B14CBCB2B7E'         /v 'DCSettingIndex'                                /T 'REG_DWORD' /D '4b0'                                    /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\SearchCompanion'                                                  /v 'DisableContentFileUpdates'                     /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\SQMClient\Windows'                                                /v 'CEIPEnable'                                    /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\SystemCertificates\AuthRoot'                                      /v 'DisableRootAutoUpdate'                         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender'                                                 /v 'DisableAntiSpyware'                            /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\CurrentVersion\NetworkList\Signatures\FirstNetwork'    /v 'Category'                                      /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers'                                              /v 'DisableHTTPPrinting'                           /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers'                                              /v 'DisableWebPnPDownload'                         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers'                                              /v 'DoNotInstallCompatibleDriverFromWindowsUpdate' /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'                                /v 'InForest'                                      /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'                                /v 'NoWarningNoElevationOnInstall'                 /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'                                /v 'Restricted'                                    /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'                                /v 'ServerList'                                    /T 'REG_SZ'    /D ''                                       /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'                                /v 'TrustedServers'                                /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'                                /v 'UpdatePromptSettings'                          /T 'REG_DWORD' /D '2'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Rpc'                                                   /v 'EnableAuthEpResolution'                        /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Rpc'                                                   /v 'RestrictRemoteClients'                         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'AllowedAudioQualityMode'                       /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'DeleteTempDirsOnExit'                          /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'DisablePasswordSaving'                         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fAllowToGetHelp'                               /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fAllowUnsolicited'                             /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDenyTSConnections'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisableAudioCapture'                          /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisableCam'                                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisableCcm'                                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisableCdm'                                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisableClip'                                  /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisableLPT'                                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fDisablePNPRedir'                              /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fEnableSmartCard'                              /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fEnableTimeZoneRedirection'                    /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fEncryptRPCTraffic'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fPromptForPassword'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'fResetBroken'                                  /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'LoggingEnabled'                                /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'MaxDisconnectionTime'                          /T 'REG_DWORD' /D 'ea60'                                   /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'MaxIdleTime'                                   /T 'REG_DWORD' /D 'dbba0'                                  /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'MinEncryptionLevel'                            /T 'REG_DWORD' /D '3'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'PerSessionTempDir'                             /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'PromptForCredsOnClient'                        /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'ShareControlMessage'                           /T 'REG_SZ'    /D 'You are about to allow other personnel to remotely control your system. You must monitor the activity until the session is closed.'     /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'UseCustomMessages'                             /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'                                     /v 'ViewMessage'                                   /T 'REG_SZ'    /D 'You are about to allow other personnel to remotely connect to your system. Sensitive data should not be displayed during this session.' /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client'                              /v 'fEnableUsbBlockDeviceBySetupClass'             /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client'                              /v 'fEnableUsbNoAckIsochWriteToDevice'             /T 'REG_DWORD' /D '50'                                     /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client'                              /v 'fEnableUsbSelectDeviceByInterface'             /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client\UsbBlockDeviceBySetupClasses' /V '1000'                                          /T 'REG_SZ'    /D '{3376f4ce-ff8d-40a2-a80f-bb4359d1415c}' /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client\UsbSelectDeviceByInterfaces'  /V '1000'                                          /T 'REG_SZ'    /D '{6bdd1fc6-810f-11d0-bec7-08002be2092f}' /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Windows File Protection'                               /V 'KnownDllList'                                  /T 'REG_SZ'    /D 'nlhtml.dll'                             /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat'                                                /V 'AITEnable'                                     /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat'                                                /V 'DisableInventory'                              /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat'                                                /V 'DisablePcaUI'                                  /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Appx'                                                     /V 'AllowAllTrustedApps'                           /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CredUI'                                                   /V 'DisablePasswordReveal'                         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Device Metadata'                                          /V 'PreventDeviceMetadataFromNetwork'              /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Settings'                                   /V 'AllowRemoteRPC'                                /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Settings'                                   /V 'DisableSendGenericDriverNotFoundToWER'         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Settings'                                   /V 'DisableSystemRestore'                          /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DriverSearching'                                          /V 'DriverServerSelection'                         /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EdgeUI'                                                   /V 'DisableHelpSticker'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EnhancedStorageDevices'                                   /V 'TCGSecurityActivationDisabled'                 /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application'                                     /V 'AutoBackupLogFiles'                            /T 'REG_SZ'    /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application'                                     /V 'MaxSize'                                       /T 'REG_DWORD' /D 'fa000'                                  /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security'                                        /V 'MaxSize'                                       /T 'REG_DWORD' /D 'fa000'                                  /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup'                                           /V 'AutoBackupLogFiles'                            /T 'REG_SZ'    /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup'                                           /V 'Enabled'                                       /T 'REG_SZ'    /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup'                                           /V 'MaxSize'                                       /T 'REG_DWORD' /D 'fa000'                                  /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\System'                                          /V 'AutoBackupLogFiles'                            /T 'REG_SZ'    /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\System'                                          /V 'MaxSize'                                       /T 'REG_DWORD' /D 'fa000'                                  /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer'                                                 /V 'NoAutoplayfornonVolume'                        /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer'                                                 /V 'NoDataExecutionPrevention'                     /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer'                                                 /V 'NoHeapTerminationOnCorruption'                 /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer'                                                 /V 'NoUseStoreOpenWith'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\GameUX'                                                   /V 'DownloadGameInfo'                              /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\GameUX'                                                   /V 'GameUpdateOptions'                             /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\GameUX'                                                   /V 'ListRecentlyPlayed'                            /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}'      /V 'NoBackgroundPolicy'                            /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}'      /V 'NOGPOListChanges'                              /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports'                                  /V 'PreventHandwritingErrorReports'                /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\HomeGroup'                                                /V 'DisableHomeGroup'                              /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer'                                                /V 'AlwaysInstallElevated'                         /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer'                                                /V 'DisableLUAPatching'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer'                                                /V 'EnableUserControl'                             /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer'                                                /V 'SafeForScripting'                              /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /V 'AllowLLTDIOOnDomain'                           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /V 'AllowLLTDIOOnPublicNet'                        /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /v 'AllowRspndrOnDomain'                           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /v 'AllowRspndrOnPublicNet'                        /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /v 'EnableLLTDIO'                                  /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /v 'EnableRspndr'                                  /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /v 'ProhibitLLTDIOOnPrivateNet'                    /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD'                                                     /v 'ProhibitRspndrOnPrivateNet'                    /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors'                                       /V 'DisableLocation'                               /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections'                                      /V 'NC_AllowNetBridge_NLA'                         /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections'                                      /V 'NC_PersonalFirewallConfig'                     /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections'                                      /V 'NC_StdDomainUserSetLocation'                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator'                       /V '@'                                             /T 'REG_SZ'    /D ''                                       /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\safer\codeidentifiers'                                    /V 'authenticodeenabled'                           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\ScriptedDiagnosticsProvider\Policy'                       /V 'DisableQueryRemoteServer'                      /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\ScriptedDiagnosticsProvider\Policy'                       /V 'EnableQueryRemoteServer'                       /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\SettingSync'                                              /V 'EnableBackupForWin8Apps'                       /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'                                                   /V 'AllowDomainPINLogon'                           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'                                                   /V 'BlockDomainPicturePassword'                    /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'                                                   /V 'DisableLockScreenAppNotifications'             /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'                                                   /V 'DontEnumerateConnectedUsers'                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'                                                   /V 'EnableSmartScreen'                             /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'                                                   /V 'EnumerateLocalUsers'                           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\TabletPC'                                                 /V 'PreventHandwritingDataSharing'                 /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\GroupPolicy'                                       /V 'fBlockNonDomain'                               /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\GroupPolicy'                                       /V 'fMinimizeConnections'                          /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\Local'                                             /V 'fBlockNonDomain'                               /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\Local'                                             /V 'fBlockRoaming'                                 /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\Local'                                             /V 'fDisablePowerManagement'                       /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\Local'                                             /V 'fMinimizeConnections'                          /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars'                                           /V 'DisableFlashConfigRegistrar'                   /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars'                                           /V 'DisableInBand802DOT11Registrar'                /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars'                                           /V 'DisableUPnPRegistrar'                          /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars'                                           /V 'DisableWPDRegistrar'                           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars'                                           /V 'EnableRegistrars'                              /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\UI'                                                   /V 'DisableWcnUi'                                  /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}'               /V 'ScenarioExecutionEnabled'                      /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'BypassDataThrottling'                          /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'ConfigureArchive'                              /T 'REG_DWORD' /D '2'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'DisableArchive'                                /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'Disabled'                                      /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'DisableQueue'                                  /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'DontSendAdditionalData'                        /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'DontShowUI'                                    /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'ForceQueue'                                    /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'LoggingDisabled'                               /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'MaxArchiveCount'                               /T 'REG_DWORD' /D '1f4'                                    /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'MaxQueueCount'                                 /T 'REG_DWORD' /D '64'                                     /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'MaxQueueSize'                                  /T 'REG_DWORD' /D '400'                                    /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'MinFreeDiskSpace'                              /T 'REG_DWORD' /D 'af0'                                    /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting'                                  /V 'QueuePesterInterval'                           /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting\Consent'                          /V 'DefaultConsent'                                /T 'REG_DWORD' /D '4'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting\Consent'                          /V 'DefaultOverrideBehavior'                       /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search'                                           /V 'AllowIndexingEncryptedStoresOrItems'           /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search'                                           /V 'PreventIndexingUncachedExchangeFolders'        /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client'                                             /V 'AllowBasic'                                    /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client'                                             /V 'AllowDigest'                                   /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client'                                             /V 'AllowUnencryptedTraffic'                       /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service'                                            /V 'AllowBasic'                                    /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service'                                            /V 'AllowUnencryptedTraffic'                       /T 'REG_DWORD' /D '0'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service'                                            /V 'DisableRunAs'                                  /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WorkplaceJoin'                                            /V '@'                                             /T 'REG_SZ'    /D ''                                       /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsMediaCenter'                                               /V 'MediaCenter'                                   /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsMediaPlayer'                                               /V 'DisableAutoUpdate'                             /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsMediaPlayer'                                               /V 'GroupPrivacyAcceptance'                        /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsStore'                                                     /V 'RemoveWindowsStore'                            /T 'REG_DWORD' /D '1'                                      /F | Out-Null
REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WMDRM'                                                            /V 'DisableOnline'                                 /T 'REG_DWORD' /D '1'                                      /F | Out-Null
